export const CONTAINER_WIDTH = 1024;
export const NUM_COLUMNS = 12;
export const GUTTER_SIZE = 10;
export const COLUMN_WIDTH = (CONTAINER_WIDTH - GUTTER_SIZE) / NUM_COLUMNS;
export const SMALL_COLUMN_IN_PIXEL = 10;
export const BIG_COLUMN_IN_PIXEL = COLUMN_WIDTH - SMALL_COLUMN_IN_PIXEL;
